# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: execute-tests
on: [push]
jobs:
  execute-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.16.0
      uses: actions/setup-node@v1
      with:
        node-version: 14.16.0
        cache: 'npm'
    - run: npm ci
    - run: npm run serve
    - run: node index.js
    - run: npm test
