# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: execute-tests
on: [push]
jobs:
  execute-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.16.0
      uses: actions/setup-node@v2
      with:
        node-version: 14.16.0
      env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          AUTH_SEED: ${{ secrets.AUTH_SEED }}
          TOKEN_TTL: ${{ secrets.TOKEN_TTL }}
    - run: |
            npm ci
            touch .env
            echo MONGO_URL="$MONGO_URL" >> .env
            echo AUTH_SEED="$AUTH_SEED" >> .env
            echo TOKEN_TTL="$TOKEN_TTL" >> .env
            npm run ci
